/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 10, 20, 21, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[4] = { 3.5554213574211886, 3.631274923461154, 1.2544628263586233, 3.4789077257377907 };
const float ei_classifier_anom_mean[4] = { 3.072650739514246, 4.442065243912564, -1.0220593318908202, 2.8165316343991624 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[10] = {
	{ ( float[4] ) { -0.4302690327167511, -0.5157585144042969, -0.45605042576789856, 0.1880578249692917 }, 0.5980749628081169 },
	{ ( float[4] ) { -0.3290398120880127, -0.37850335240364075, 0.14749404788017273, -0.5175421237945557 }, 0.6542907989231638 },
	{ ( float[4] ) { 0.7905887961387634, 1.096022129058838, 1.1115347146987915, -0.8244106769561768 }, 2.3656984038246223 },
	{ ( float[4] ) { -0.09615929424762726, 0.17192387580871582, 1.6955640316009521, -0.30946528911590576 }, 1.8793978936700775 },
	{ ( float[4] ) { -0.5398526191711426, -0.5995153784751892, -1.0127919912338257, 0.9784511923789978 }, 0.6955306962627714 },
	{ ( float[4] ) { 2.086632251739502, 1.764082431793213, 0.9194198250770569, -0.8863421678543091 }, 1.711206206352889 },
	{ ( float[4] ) { -0.8050190210342407, -0.6507596969604492, -1.7849925756454468, 2.1953675746917725 }, 0.6983371664579998 },
	{ ( float[4] ) { 3.094244956970215, 4.224006175994873, 0.9576370716094971, -0.5145342946052551 }, 2.1599142232871262 },
	{ ( float[4] ) { -0.010327845811843872, -0.04280847683548927, 0.7279984354972839, -0.8842476606369019 }, 1.0876545065847454 },
	{ ( float[4] ) { 4.057709693908691, 2.495816230773926, 0.8436998128890991, -0.6405178904533386 }, 1.7640114124003214 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
