/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 13, 22, 35, 39 };

// (before - mean) / scale
const float ei_classifier_anom_scale[4] = { 5.022338740021979, 1.409742726925236, 1.3728148677488132, 0.6860386713574759 };
const float ei_classifier_anom_mean[4] = { 4.4686170229592435, 0.7943569368708361, 0.9295556043701224, 0.6139560103089761 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[10] = {
	{ ( float[4] ) { -0.8655205368995667, -1.8734816312789917, -1.9383792877197266, -0.8774295449256897 }, 0.9512056957476054 },
	{ ( float[4] ) { -0.6750153303146362, -0.5344935059547424, -0.4930539131164551, -0.745311975479126 }, 1.301672599327782 },
	{ ( float[4] ) { -0.29219523072242737, 0.24824808537960052, 0.2507035434246063, -0.35861048102378845 }, 0.7174908771148529 },
	{ ( float[4] ) { -0.5285941362380981, -0.18123586475849152, 0.01024018693715334, -0.5650193095207214 }, 0.8779361042118226 },
	{ ( float[4] ) { 1.2556055784225464, 1.0292190313339233, 0.9462552666664124, 1.5171805620193481 }, 1.177730696835654 },
	{ ( float[4] ) { 3.377385377883911, 1.3539220094680786, 1.0975382328033447, 2.8711116313934326 }, 1.059227816336539 },
	{ ( float[4] ) { 0.5584284663200378, 0.7297040224075317, 0.895423948764801, 0.953728437423706 }, 0.9690486347416549 },
	{ ( float[4] ) { -0.8837217688560486, -2.826908826828003, -2.955561876296997, -0.8915848135948181 }, 0.8657863384171247 },
	{ ( float[4] ) { 2.0825772285461426, 1.2021300792694092, 0.8984962105751038, 2.0961031913757324 }, 1.0123312340373454 },
	{ ( float[4] ) { 0.13108119368553162, 0.6290543675422668, 0.5077559947967529, 0.1843695342540741 }, 0.9966256376329927 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
